export const categoriesMocks = [{
  id: '1',
  name: 'Clarify',
  phrases: [
    { text: 'Could you say that again?' },
    { text: 'Sorry, I didn\u2019t catch that.' },
    { text: 'What do you mean by that?' },
    { text: 'Could you explain that differently?' },
    { text: 'Can you give me an example?' },
    { text: 'I\u2019m not sure I follow.' },
    { text: 'Could you slow down a bit?' },
    { text: 'What exactly do you mean?' },
    { text: 'Sorry, could you repeat that?' },
    { text: 'I didn\u2019t quite get that.' },
    { text: 'Can you put that another way?' },
    { text: 'What does that mean?' },
    { text: 'Could you be more specific?' },
    { text: 'I\u2019m a bit confused.' },
    { text: 'Can you say that more simply?' },
    { text: 'So you\u2019re saying that...?' },
    { text: 'Do you mean...?' },
    { text: 'Just to make sure I understand...' },
    { text: 'If I understood correctly...' },
    { text: 'In other words...?' },
    { text: 'Let me check I got that right.' },
    { text: 'So what you mean is...?' },
    { text: 'Wait, I\u2019m lost.' },
    { text: 'Can you go over that again?' },
    { text: 'I\u2019m not sure what you mean.' },
    { text: 'Sorry, one more time?' },
    { text: 'Could you speak up a little?' },
    { text: 'Hang on, what was that?' },
    { text: 'Which part do you mean?' },
    { text: 'Sorry, I zoned out for a second.' },
    { text: 'Could you break that down for me?' },
    { text: 'What do you mean exactly?' },
    { text: 'That went over my head.' },
    { text: 'Can you unpack that a little?' },
    { text: 'Let me see if I got this right.' },
    { text: 'Hold on, I want to make sure...' },
    { text: 'Am I understanding you correctly?' },
    { text: 'So basically you\u2019re saying...?' },
    { text: 'I think I missed something.' },
    { text: 'Could you walk me through that?' },
  ],
}, {
  id: '2',
  name: 'Agree',
  phrases: [
    { text: 'I totally agree.' },
    { text: 'That\u2019s a great point.' },
    { text: 'Exactly.' },
    { text: 'You\u2019re absolutely right.' },
    { text: 'I see what you mean.' },
    { text: 'That makes sense.' },
    { text: 'I couldn\u2019t agree more.' },
    { text: 'Fair enough.' },
    { text: 'Good point.' },
    { text: 'That\u2019s true.' },
    { text: 'I think so too.' },
    { text: 'I was thinking the same thing.' },
    { text: 'That\u2019s exactly how I feel.' },
    { text: 'I\u2019m with you on that.' },
    { text: 'You\u2019ve got a point there.' },
    { text: 'That\u2019s hard to argue with.' },
    { text: 'Absolutely.' },
    { text: 'Definitely.' },
    { text: 'I hear you.' },
    { text: 'No doubt about it.' },
    { text: 'You took the words right out of my mouth.' },
    { text: 'I can\u2019t argue with that.' },
    { text: 'That\u2019s spot on.' },
    { text: 'I second that.' },
    { text: 'Tell me about it.' },
    { text: 'You\u2019re right about that.' },
    { text: 'Sounds about right.' },
    { text: 'I completely agree.' },
    { text: 'That\u2019s very true.' },
    { text: 'You make a good case.' },
    { text: 'I\u2019d go along with that.' },
    { text: 'That\u2019s what I was going to say.' },
    { text: 'Precisely.' },
    { text: 'I feel the same way.' },
    { text: 'Without a doubt.' },
    { text: 'I\u2019m on board with that.' },
    { text: 'I\u2019ll go with that.' },
    { text: 'That seems right to me.' },
    { text: 'I\u2019d say so too.' },
    { text: 'You nailed it.' },
  ],
}, {
  id: '3',
  name: 'Disagree',
  phrases: [
    { text: 'I\u2019m not so sure about that.' },
    { text: 'I see it differently.' },
    { text: 'I don\u2019t quite agree.' },
    { text: 'I respectfully disagree.' },
    { text: 'I wouldn\u2019t go that far.' },
    { text: 'That\u2019s not how I see it.' },
    { text: 'I have my doubts about that.' },
    { text: 'I\u2019m not convinced.' },
    { text: 'Not necessarily.' },
    { text: 'I see your point, but...' },
    { text: 'I beg to differ.' },
    { text: 'That\u2019s one way to look at it.' },
    { text: 'I\u2019m not sure that\u2019s right.' },
    { text: 'I think there\u2019s more to it.' },
    { text: 'I\u2019d push back on that.' },
    { text: 'I take a different view.' },
    { text: 'I don\u2019t think that\u2019s the whole picture.' },
    { text: 'I wouldn\u2019t say that.' },
    { text: 'I see where you\u2019re coming from, but...' },
    { text: 'That doesn\u2019t quite add up.' },
    { text: 'With all due respect...' },
    { text: 'I\u2019m going to have to disagree.' },
    { text: 'That\u2019s debatable.' },
    { text: 'I have a hard time with that.' },
    { text: 'Not exactly.' },
    { text: 'I think it\u2019s more nuanced than that.' },
    { text: 'That might be a bit of a stretch.' },
    { text: 'I\u2019m on the fence about that.' },
    { text: 'I wouldn\u2019t put it that way.' },
    { text: 'I think we see this differently.' },
    { text: 'I\u2019m not entirely sure about that.' },
    { text: 'That\u2019s a fair point, but...' },
    { text: 'I can see that, but I\u2019d argue...' },
    { text: 'I lean the other way.' },
    { text: 'I have reservations about that.' },
    { text: 'That doesn\u2019t sit right with me.' },
    { text: 'I partially agree, but...' },
    { text: 'I\u2019d challenge that.' },
    { text: 'I think there\u2019s another side to it.' },
    { text: 'I\u2019m skeptical about that.' },
  ],
}, {
  id: '4',
  name: 'Stall',
  phrases: [
    { text: 'Let me think about that.' },
    { text: 'That\u2019s a good question.' },
    { text: 'Hmm, how do I put this...' },
    { text: 'Give me a second.' },
    { text: 'I need to think about that.' },
    { text: 'Well, it\u2019s hard to say.' },
    { text: 'That\u2019s a tough one.' },
    { text: 'Let me see...' },
    { text: 'How should I put this...' },
    { text: 'I\u2019m not sure where to start.' },
    { text: 'Where do I begin?' },
    { text: 'That\u2019s tricky.' },
    { text: 'Good question, actually.' },
    { text: 'I haven\u2019t really thought about it.' },
    { text: 'Off the top of my head...' },
    { text: 'Well, the thing is...' },
    { text: 'I mean...' },
    { text: 'You know what...' },
    { text: 'So basically...' },
    { text: 'The thing is...' },
    { text: 'It\u2019s complicated.' },
    { text: 'That depends on a lot of things.' },
    { text: 'I\u2019m still figuring that out.' },
    { text: 'I\u2019ll have to get back to you on that.' },
    { text: 'I don\u2019t have a strong opinion yet.' },
    { text: 'I\u2019m torn on that, actually.' },
    { text: 'Part of me thinks... but also...' },
    { text: 'I\u2019ve been going back and forth on that.' },
    { text: 'That\u2019s something I need to consider.' },
    { text: 'I\u2019m still making up my mind.' },
    { text: 'To be fair...' },
    { text: 'What I will say is...' },
    { text: 'Well, on one hand...' },
    { text: 'It really depends.' },
    { text: 'I want to say... but I\u2019m not sure.' },
    { text: 'Actually, hold on...' },
    { text: 'Wait, let me rephrase that.' },
    { text: 'Sorry, let me start over.' },
    { text: 'What I\u2019m trying to say is...' },
    { text: 'Bear with me for a moment.' },
  ],
}, {
  id: '5',
  name: 'Ask',
  phrases: [
    { text: 'What do you think?' },
    { text: 'How do you feel about that?' },
    { text: 'What\u2019s your take on this?' },
    { text: 'Do you agree?' },
    { text: 'Why do you think so?' },
    { text: 'What makes you say that?' },
    { text: 'Can you tell me more?' },
    { text: 'What happened next?' },
    { text: 'How come?' },
    { text: 'Like what, for example?' },
    { text: 'Such as?' },
    { text: 'In what way?' },
    { text: 'What do you mean by that?' },
    { text: 'How so?' },
    { text: 'Is that really true?' },
    { text: 'Are you sure about that?' },
    { text: 'And then what?' },
    { text: 'What would you do?' },
    { text: 'How would you handle that?' },
    { text: 'Have you ever experienced that?' },
    { text: 'What\u2019s the main reason?' },
    { text: 'Does everyone feel that way?' },
    { text: 'Is that common?' },
    { text: 'Has it always been like that?' },
    { text: 'What\u2019s the alternative?' },
    { text: 'Is there another way to see this?' },
    { text: 'Who told you that?' },
    { text: 'Where did you hear that?' },
    { text: 'What\u2019s the biggest challenge?' },
    { text: 'What surprised you the most?' },
    { text: 'Would you recommend it?' },
    { text: 'How did that make you feel?' },
    { text: 'What would you change?' },
    { text: 'What\u2019s the most important part?' },
    { text: 'Do you think it matters?' },
    { text: 'Why is that important?' },
    { text: 'What are the pros and cons?' },
    { text: 'Is there a downside?' },
    { text: 'What\u2019s your experience with that?' },
    { text: 'How does that compare?' },
  ],
}]
