export const categoriesMocks = [{
  id: '1',
  name: 'Clarify',
  label: 'Ask for more detail',
  phrases: [
    { text: 'Could you say that again?', context: 'Could you say that again? I missed the part about the deadline.' },
    { text: 'Sorry, I didn\u2019t catch that.', context: 'Sorry, I didn\u2019t catch that \u2014 did you say Tuesday or Thursday?' },
    { text: 'What do you mean by that?', context: 'What do you mean by that \u2014 are you talking about the cost or the timeline?' },
    { text: 'Could you explain that differently?', context: 'Could you explain that differently? I\u2019m not sure I follow the technical part.' },
    { text: 'Can you give me an example?', context: 'Can you give me an example? I want to see how this works in practice.' },
    { text: 'I\u2019m not sure I follow.', context: 'I\u2019m not sure I follow \u2014 are we still talking about the original plan?' },
    { text: 'Could you slow down a bit?', context: 'Could you slow down a bit? I\u2019m trying to take notes.' },
    { text: 'What exactly do you mean?', context: 'What exactly do you mean? Are you suggesting we cancel the whole thing?' },
    { text: 'Sorry, could you repeat that?', context: 'Sorry, could you repeat that? There was a lot of noise on the line.' },
    { text: 'I didn\u2019t quite get that.', context: 'I didn\u2019t quite get that \u2014 was that about the marketing budget or the dev budget?' },
    { text: 'Can you put that another way?', context: 'Can you put that another way? I\u2019m struggling to see how it applies to our situation.' },
    { text: 'What does that mean?', context: 'What does that mean for the rest of the team \u2014 will they need to adjust too?' },
    { text: 'Could you be more specific?', context: 'Could you be more specific about what kind of changes you have in mind?' },
    { text: 'I\u2019m a bit confused.', context: 'I\u2019m a bit confused \u2014 I thought we already agreed on the scope last week.' },
    { text: 'Can you say that more simply?', context: 'Can you say that more simply? Not everyone here has a technical background.' },
    { text: 'So you\u2019re saying that...?', context: 'So you\u2019re saying that we should hold off until the next quarter?' },
    { text: 'Do you mean...?', context: 'Do you mean we need to redo the entire proposal, or just the summary?' },
    { text: 'Just to make sure I understand...', context: 'Just to make sure I understand \u2014 the new policy starts next month, right?' },
    { text: 'If I understood correctly...', context: 'If I understood correctly, you want us to merge both projects into one?' },
    { text: 'In other words...?', context: 'In other words, you\u2019re saying the partnership isn\u2019t going to happen?' },
    { text: 'Let me check I got that right.', context: 'Let me check I got that right \u2014 we ship the MVP first, then add analytics?' },
    { text: 'So what you mean is...?', context: 'So what you mean is the client wants a completely different approach?' },
    { text: 'Wait, I\u2019m lost.', context: 'Wait, I\u2019m lost \u2014 when did the requirements change?' },
    { text: 'Can you go over that again?', context: 'Can you go over that again? I want to make sure I have the steps right.' },
    { text: 'I\u2019m not sure what you mean.', context: 'I\u2019m not sure what you mean by "flexible" in this context.' },
    { text: 'Sorry, one more time?', context: 'Sorry, one more time? I didn\u2019t hear the name of the tool you mentioned.' },
    { text: 'Could you speak up a little?', context: 'Could you speak up a little? It\u2019s hard to hear you in this room.' },
    { text: 'Hang on, what was that?', context: 'Hang on, what was that about the contract \u2014 are there new terms?' },
    { text: 'Which part do you mean?', context: 'Which part do you mean \u2014 the onboarding flow or the dashboard?' },
    { text: 'Sorry, I zoned out for a second.', context: 'Sorry, I zoned out for a second \u2014 can you repeat the last point?' },
    { text: 'Could you break that down for me?', context: 'Could you break that down for me? The numbers don\u2019t add up in my head.' },
    { text: 'What do you mean exactly?', context: 'What do you mean exactly \u2014 should we pause development or just slow down?' },
    { text: 'That went over my head.', context: 'That went over my head \u2014 could you explain the architecture part again?' },
    { text: 'Can you unpack that a little?', context: 'Can you unpack that a little? I want to understand the reasoning behind it.' },
    { text: 'Let me see if I got this right.', context: 'Let me see if I got this right \u2014 you\u2019re proposing we launch in two phases?' },
    { text: 'Hold on, I want to make sure...', context: 'Hold on, I want to make sure \u2014 does this affect the release date?' },
    { text: 'Am I understanding you correctly?', context: 'Am I understanding you correctly \u2014 you want to replace the entire backend?' },
    { text: 'So basically you\u2019re saying...?', context: 'So basically you\u2019re saying we need more people on the team?' },
    { text: 'I think I missed something.', context: 'I think I missed something \u2014 why are we changing the vendor?' },
    { text: 'Could you walk me through that?', context: 'Could you walk me through that? I\u2019d like to understand the full process.' },
  ],
}, {
  id: '2',
  name: 'Agree',
  label: 'Express agreement',
  phrases: [
    { text: 'I totally agree.', context: 'I totally agree \u2014 we should focus on quality over speed right now.' },
    { text: 'That\u2019s a great point.', context: 'That\u2019s a great point \u2014 we never considered how this affects the support team.' },
    { text: 'Exactly.', context: 'Exactly \u2014 that\u2019s what I\u2019ve been trying to say all along.' },
    { text: 'You\u2019re absolutely right.', context: 'You\u2019re absolutely right \u2014 waiting would only make the problem worse.' },
    { text: 'I see what you mean.', context: 'I see what you mean \u2014 the current flow really is too complicated for new users.' },
    { text: 'That makes sense.', context: 'That makes sense, especially given how tight the budget is this quarter.' },
    { text: 'I couldn\u2019t agree more.', context: 'I couldn\u2019t agree more \u2014 documentation has been our weakest link for months.' },
    { text: 'Fair enough.', context: 'Fair enough \u2014 I see why you\u2019d want to test it before committing.' },
    { text: 'Good point.', context: 'Good point \u2014 I hadn\u2019t thought about the legal implications.' },
    { text: 'That\u2019s true.', context: 'That\u2019s true \u2014 remote teams do need more structure, not less.' },
    { text: 'I think so too.', context: 'I think so too \u2014 the rebrand is long overdue.' },
    { text: 'I was thinking the same thing.', context: 'I was thinking the same thing \u2014 we should bring in an external reviewer.' },
    { text: 'That\u2019s exactly how I feel.', context: 'That\u2019s exactly how I feel \u2014 transparency is more important than polish.' },
    { text: 'I\u2019m with you on that.', context: 'I\u2019m with you on that \u2014 scaling too fast would hurt us in the long run.' },
    { text: 'You\u2019ve got a point there.', context: 'You\u2019ve got a point there \u2014 a simpler onboarding could reduce churn significantly.' },
    { text: 'That\u2019s hard to argue with.', context: 'That\u2019s hard to argue with \u2014 the data clearly shows a downward trend.' },
    { text: 'Absolutely.', context: 'Absolutely \u2014 we need to fix the basics before adding new features.' },
    { text: 'Definitely.', context: 'Definitely \u2014 this is the right time to invest in infrastructure.' },
    { text: 'I hear you.', context: 'I hear you \u2014 it\u2019s been a tough quarter for the whole team.' },
    { text: 'No doubt about it.', context: 'No doubt about it \u2014 the redesign was the best decision we made this year.' },
    { text: 'You took the words right out of my mouth.', context: 'You took the words right out of my mouth \u2014 that\u2019s exactly the problem.' },
    { text: 'I can\u2019t argue with that.', context: 'I can\u2019t argue with that \u2014 the numbers speak for themselves.' },
    { text: 'That\u2019s spot on.', context: 'That\u2019s spot on \u2014 the bottleneck is definitely in the approval process.' },
    { text: 'I second that.', context: 'I second that \u2014 let\u2019s move forward with the new approach.' },
    { text: 'Tell me about it.', context: 'Tell me about it \u2014 I\u2019ve been dealing with the same issue all week.' },
    { text: 'You\u2019re right about that.', context: 'You\u2019re right about that \u2014 we underestimated the migration effort.' },
    { text: 'Sounds about right.', context: 'Sounds about right \u2014 two sprints should be enough for the first phase.' },
    { text: 'I completely agree.', context: 'I completely agree \u2014 user feedback should drive our next priorities.' },
    { text: 'That\u2019s very true.', context: 'That\u2019s very true \u2014 most of our bugs come from that one legacy module.' },
    { text: 'You make a good case.', context: 'You make a good case \u2014 maybe we should reconsider the timeline.' },
    { text: 'I\u2019d go along with that.', context: 'I\u2019d go along with that \u2014 a phased rollout seems safer.' },
    { text: 'That\u2019s what I was going to say.', context: 'That\u2019s what I was going to say \u2014 the API needs versioning before we ship.' },
    { text: 'Precisely.', context: 'Precisely \u2014 the problem isn\u2019t the tool, it\u2019s how we\u2019re using it.' },
    { text: 'I feel the same way.', context: 'I feel the same way \u2014 weekly syncs would help us stay aligned.' },
    { text: 'Without a doubt.', context: 'Without a doubt \u2014 this feature has the highest ROI on the roadmap.' },
    { text: 'I\u2019m on board with that.', context: 'I\u2019m on board with that \u2014 let\u2019s allocate more resources to testing.' },
    { text: 'I\u2019ll go with that.', context: 'I\u2019ll go with that \u2014 your suggestion covers all the edge cases.' },
    { text: 'That seems right to me.', context: 'That seems right to me \u2014 starting small and iterating is the safest bet.' },
    { text: 'I\u2019d say so too.', context: 'I\u2019d say so too \u2014 the market is ready for what we\u2019re building.' },
    { text: 'You nailed it.', context: 'You nailed it \u2014 that\u2019s the exact reason we\u2019ve been losing users.' },
  ],
}, {
  id: '3',
  name: 'Disagree',
  label: 'Express disagreement',
  phrases: [
    { text: 'I\u2019m not so sure about that.', context: 'I\u2019m not so sure about that \u2014 the data doesn\u2019t really support that conclusion.' },
    { text: 'I see it differently.', context: 'I see it differently \u2014 I think the problem is in the process, not the people.' },
    { text: 'I don\u2019t quite agree.', context: 'I don\u2019t quite agree \u2014 I think there\u2019s a simpler solution we\u2019re overlooking.' },
    { text: 'I respectfully disagree.', context: 'I respectfully disagree \u2014 cutting the QA phase would create more problems than it solves.' },
    { text: 'I wouldn\u2019t go that far.', context: 'I wouldn\u2019t go that far \u2014 the product has issues, but it\u2019s not a total failure.' },
    { text: 'That\u2019s not how I see it.', context: 'That\u2019s not how I see it \u2014 I think the delay actually gave us time to improve.' },
    { text: 'I have my doubts about that.', context: 'I have my doubts about that \u2014 the last time we tried this approach it didn\u2019t work.' },
    { text: 'I\u2019m not convinced.', context: 'I\u2019m not convinced that automation alone will fix our delivery speed.' },
    { text: 'Not necessarily.', context: 'Not necessarily \u2014 a bigger team doesn\u2019t always mean faster results.' },
    { text: 'I see your point, but...', context: 'I see your point, but I think we\u2019re ignoring the long-term maintenance cost.' },
    { text: 'I beg to differ.', context: 'I beg to differ \u2014 our competitors moved fast and it hurt their reputation.' },
    { text: 'That\u2019s one way to look at it.', context: 'That\u2019s one way to look at it, but the customer feedback tells a different story.' },
    { text: 'I\u2019m not sure that\u2019s right.', context: 'I\u2019m not sure that\u2019s right \u2014 I remember the numbers being quite different.' },
    { text: 'I think there\u2019s more to it.', context: 'I think there\u2019s more to it \u2014 the drop in engagement started before the redesign.' },
    { text: 'I\u2019d push back on that.', context: 'I\u2019d push back on that \u2014 skipping user research has cost us before.' },
    { text: 'I take a different view.', context: 'I take a different view \u2014 I believe the free tier is what drives our growth.' },
    { text: 'I don\u2019t think that\u2019s the whole picture.', context: 'I don\u2019t think that\u2019s the whole picture \u2014 there are internal factors we haven\u2019t discussed.' },
    { text: 'I wouldn\u2019t say that.', context: 'I wouldn\u2019t say that \u2014 the team has actually improved a lot since last quarter.' },
    { text: 'I see where you\u2019re coming from, but...', context: 'I see where you\u2019re coming from, but the market conditions are very different now.' },
    { text: 'That doesn\u2019t quite add up.', context: 'That doesn\u2019t quite add up \u2014 how can we cut costs and expand at the same time?' },
    { text: 'With all due respect...', context: 'With all due respect, I think we\u2019re solving the wrong problem here.' },
    { text: 'I\u2019m going to have to disagree.', context: 'I\u2019m going to have to disagree \u2014 launching without mobile support would be a mistake.' },
    { text: 'That\u2019s debatable.', context: 'That\u2019s debatable \u2014 not every company in our space has seen the same trend.' },
    { text: 'I have a hard time with that.', context: 'I have a hard time with that \u2014 removing the feature would upset our most loyal users.' },
    { text: 'Not exactly.', context: 'Not exactly \u2014 the issue is less about the tool and more about the workflow.' },
    { text: 'I think it\u2019s more nuanced than that.', context: 'I think it\u2019s more nuanced than that \u2014 both teams share responsibility for the outcome.' },
    { text: 'That might be a bit of a stretch.', context: 'That might be a bit of a stretch \u2014 we can\u2019t compare ourselves to a company ten times our size.' },
    { text: 'I\u2019m on the fence about that.', context: 'I\u2019m on the fence about that \u2014 the upside is real but so is the risk.' },
    { text: 'I wouldn\u2019t put it that way.', context: 'I wouldn\u2019t put it that way \u2014 the project wasn\u2019t a failure, we just pivoted.' },
    { text: 'I think we see this differently.', context: 'I think we see this differently \u2014 for me, retention matters more than acquisition right now.' },
    { text: 'I\u2019m not entirely sure about that.', context: 'I\u2019m not entirely sure about that \u2014 the survey sample was pretty small.' },
    { text: 'That\u2019s a fair point, but...', context: 'That\u2019s a fair point, but it doesn\u2019t account for the seasonal variation.' },
    { text: 'I can see that, but I\u2019d argue...', context: 'I can see that, but I\u2019d argue the root cause is deeper than what\u2019s visible.' },
    { text: 'I lean the other way.', context: 'I lean the other way \u2014 I\u2019d rather invest in the existing product than build something new.' },
    { text: 'I have reservations about that.', context: 'I have reservations about that \u2014 signing a two-year contract feels premature.' },
    { text: 'That doesn\u2019t sit right with me.', context: 'That doesn\u2019t sit right with me \u2014 accessibility shouldn\u2019t be treated as optional.' },
    { text: 'I partially agree, but...', context: 'I partially agree, but I think we need more data before making that call.' },
    { text: 'I\u2019d challenge that.', context: 'I\u2019d challenge that \u2014 our own metrics show the opposite trend.' },
    { text: 'I think there\u2019s another side to it.', context: 'I think there\u2019s another side to it \u2014 the vendors have their own constraints too.' },
    { text: 'I\u2019m skeptical about that.', context: 'I\u2019m skeptical about that \u2014 AI hype doesn\u2019t always translate into real value.' },
  ],
}, {
  id: '4',
  name: 'Stall',
  label: 'Buy yourself time',
  phrases: [
    { text: 'Let me think about that.', context: 'Let me think about that \u2014 I don\u2019t want to give you a half-baked answer.' },
    { text: 'That\u2019s a good question.', context: 'That\u2019s a good question \u2014 I honestly haven\u2019t considered that angle before.' },
    { text: 'Hmm, how do I put this...', context: 'Hmm, how do I put this... the situation is a bit more complicated than it looks.' },
    { text: 'Give me a second.', context: 'Give me a second \u2014 I want to pull up the numbers before I answer.' },
    { text: 'I need to think about that.', context: 'I need to think about that \u2014 there are a few trade-offs I want to weigh.' },
    { text: 'Well, it\u2019s hard to say.', context: 'Well, it\u2019s hard to say \u2014 it really depends on how the client responds.' },
    { text: 'That\u2019s a tough one.', context: 'That\u2019s a tough one \u2014 both options have real downsides.' },
    { text: 'Let me see...', context: 'Let me see... I think we discussed this in last week\u2019s meeting.' },
    { text: 'How should I put this...', context: 'How should I put this... I don\u2019t think the team is fully aligned yet.' },
    { text: 'I\u2019m not sure where to start.', context: 'I\u2019m not sure where to start \u2014 there\u2019s a lot of history behind this decision.' },
    { text: 'Where do I begin?', context: 'Where do I begin? The project has gone through three major pivots already.' },
    { text: 'That\u2019s tricky.', context: 'That\u2019s tricky \u2014 we\u2019d need buy-in from at least two other departments.' },
    { text: 'Good question, actually.', context: 'Good question, actually \u2014 I don\u2019t think anyone has asked that before.' },
    { text: 'I haven\u2019t really thought about it.', context: 'I haven\u2019t really thought about it from that perspective \u2014 let me sit with it.' },
    { text: 'Off the top of my head...', context: 'Off the top of my head, I\u2019d say three to four weeks, but let me confirm.' },
    { text: 'Well, the thing is...', context: 'Well, the thing is, we don\u2019t actually have the data to make that call yet.' },
    { text: 'I mean...', context: 'I mean, it\u2019s not wrong, but I wouldn\u2019t call it the best approach either.' },
    { text: 'You know what...', context: 'You know what, let me check with the team first before I commit to anything.' },
    { text: 'So basically...', context: 'So basically, we\u2019re choosing between speed and reliability here.' },
    { text: 'The thing is...', context: 'The thing is, we tried something similar last year and it didn\u2019t take off.' },
    { text: 'It\u2019s complicated.', context: 'It\u2019s complicated \u2014 there are legal and technical sides to consider.' },
    { text: 'That depends on a lot of things.', context: 'That depends on a lot of things \u2014 budget, timing, and team capacity, to name a few.' },
    { text: 'I\u2019m still figuring that out.', context: 'I\u2019m still figuring that out \u2014 I should have a clearer picture by Friday.' },
    { text: 'I\u2019ll have to get back to you on that.', context: 'I\u2019ll have to get back to you on that \u2014 I need to run the numbers first.' },
    { text: 'I don\u2019t have a strong opinion yet.', context: 'I don\u2019t have a strong opinion yet \u2014 I want to hear what the rest of the team thinks.' },
    { text: 'I\u2019m torn on that, actually.', context: 'I\u2019m torn on that, actually \u2014 both sides make valid points.' },
    { text: 'Part of me thinks... but also...', context: 'Part of me thinks we should wait, but also, the window might close soon.' },
    { text: 'I\u2019ve been going back and forth on that.', context: 'I\u2019ve been going back and forth on that \u2014 every time I decide, new info changes things.' },
    { text: 'That\u2019s something I need to consider.', context: 'That\u2019s something I need to consider \u2014 I hadn\u2019t factored in the compliance angle.' },
    { text: 'I\u2019m still making up my mind.', context: 'I\u2019m still making up my mind \u2014 I\u2019ll have an answer after the stakeholder review.' },
    { text: 'To be fair...', context: 'To be fair, they did warn us about this risk early on.' },
    { text: 'What I will say is...', context: 'What I will say is, we\u2019re in a much better position than we were six months ago.' },
    { text: 'Well, on one hand...', context: 'Well, on one hand, it saves time \u2014 but on the other, it adds technical debt.' },
    { text: 'It really depends.', context: 'It really depends on whether the client is open to extending the deadline.' },
    { text: 'I want to say... but I\u2019m not sure.', context: 'I want to say yes, but I\u2019m not sure we have the bandwidth this sprint.' },
    { text: 'Actually, hold on...', context: 'Actually, hold on \u2014 I just remembered there\u2019s a dependency we haven\u2019t discussed.' },
    { text: 'Wait, let me rephrase that.', context: 'Wait, let me rephrase that \u2014 what I meant was we should test it first.' },
    { text: 'Sorry, let me start over.', context: 'Sorry, let me start over \u2014 I think I was overcomplicating things.' },
    { text: 'What I\u2019m trying to say is...', context: 'What I\u2019m trying to say is, we need a clearer goal before we start building.' },
    { text: 'Bear with me for a moment.', context: 'Bear with me for a moment \u2014 I\u2019m trying to connect a few dots here.' },
  ],
}, {
  id: '5',
  name: 'Ask',
  label: 'Ask a question',
  phrases: [
    { text: 'What do you think?', context: 'What do you think \u2014 should we go with the safe option or take the risk?' },
    { text: 'How do you feel about that?', context: 'How do you feel about that \u2014 does the new schedule work for your team?' },
    { text: 'What\u2019s your take on this?', context: 'What\u2019s your take on this \u2014 is the feature worth the engineering effort?' },
    { text: 'Do you agree?', context: 'Do you agree, or do you think we should approach it differently?' },
    { text: 'Why do you think so?', context: 'Why do you think so? I\u2019m curious about the reasoning behind your view.' },
    { text: 'What makes you say that?', context: 'What makes you say that \u2014 did something specific happen with the client?' },
    { text: 'Can you tell me more?', context: 'Can you tell me more about how the integration is supposed to work?' },
    { text: 'What happened next?', context: 'What happened next \u2014 did they accept the proposal or push back?' },
    { text: 'How come?', context: 'How come? I thought the project was going well.' },
    { text: 'Like what, for example?', context: 'Like what, for example? I\u2019d love to hear a specific use case.' },
    { text: 'Such as?', context: 'Such as? What kind of improvements are you thinking of?' },
    { text: 'In what way?', context: 'In what way \u2014 is it the design, the performance, or something else?' },
    { text: 'What do you mean by that?', context: 'What do you mean by that \u2014 are you saying we should change direction?' },
    { text: 'How so?', context: 'How so? I didn\u2019t think the new policy would affect us directly.' },
    { text: 'Is that really true?', context: 'Is that really true? I\u2019ve heard conflicting reports from other teams.' },
    { text: 'Are you sure about that?', context: 'Are you sure about that? The last estimate turned out to be way off.' },
    { text: 'And then what?', context: 'And then what \u2014 do we wait for approval or start building in parallel?' },
    { text: 'What would you do?', context: 'What would you do if you were in charge of the migration?' },
    { text: 'How would you handle that?', context: 'How would you handle that \u2014 would you bring it up directly or escalate?' },
    { text: 'Have you ever experienced that?', context: 'Have you ever experienced that \u2014 a launch that went completely sideways?' },
    { text: 'What\u2019s the main reason?', context: 'What\u2019s the main reason for switching providers \u2014 cost, reliability, or both?' },
    { text: 'Does everyone feel that way?', context: 'Does everyone feel that way, or is it mainly coming from one team?' },
    { text: 'Is that common?', context: 'Is that common in the industry, or is it specific to our setup?' },
    { text: 'Has it always been like that?', context: 'Has it always been like that, or did something change recently?' },
    { text: 'What\u2019s the alternative?', context: 'What\u2019s the alternative if we can\u2019t get the budget approved in time?' },
    { text: 'Is there another way to see this?', context: 'Is there another way to see this \u2014 maybe it\u2019s actually an opportunity?' },
    { text: 'Who told you that?', context: 'Who told you that \u2014 was it from the leadership meeting this morning?' },
    { text: 'Where did you hear that?', context: 'Where did you hear that? I haven\u2019t seen any official announcement.' },
    { text: 'What\u2019s the biggest challenge?', context: 'What\u2019s the biggest challenge you\u2019re facing with the current system?' },
    { text: 'What surprised you the most?', context: 'What surprised you the most about the user research findings?' },
    { text: 'Would you recommend it?', context: 'Would you recommend it for a team our size, or is it better for larger orgs?' },
    { text: 'How did that make you feel?', context: 'How did that make you feel when they decided to shelve the project?' },
    { text: 'What would you change?', context: 'What would you change if you could go back to the start of the project?' },
    { text: 'What\u2019s the most important part?', context: 'What\u2019s the most important part \u2014 the timeline or the feature set?' },
    { text: 'Do you think it matters?', context: 'Do you think it matters at this stage, or can we address it later?' },
    { text: 'Why is that important?', context: 'Why is that important \u2014 what happens if we skip that step?' },
    { text: 'What are the pros and cons?', context: 'What are the pros and cons of building in-house versus outsourcing it?' },
    { text: 'Is there a downside?', context: 'Is there a downside to launching earlier, or is it all upside?' },
    { text: 'What\u2019s your experience with that?', context: 'What\u2019s your experience with that tool \u2014 did it live up to expectations?' },
    { text: 'How does that compare?', context: 'How does that compare to what we had before \u2014 is it actually faster?' },
  ],
}]
